TypFiles := $(wildcard typ/*.typ)
HTMLFiles := $(TypFiles:typ/%.typ=%.html)
PDFFiles := $(TypFiles:typ/%.typ=pdf/%.pdf)

.PHONY: help

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9\/_\.-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

build-pages: $(HTMLFiles) $(PDFFiles) ## Build the pages

%.html: typ/%.typ
	awk '/^---$$/{f=!f;next}f' $< > tmp.html
	awk '/^---$$/{f=!f;next}!f' $< > tmp.typ
	pandoc tmp.typ -f typst -t html -o $@ --self-contained --css=tufte.css \
		-H ./tmp.html
	# This is a hack to remove the title generated by pandoc.
	sed -i '0,/<title>/s/<title>.*<\/title>//' $@
	rm tmp.html tmp.typ

pdf/%.pdf: $(HTMLFiles)
	wkhtmltopdf $< $@

dev: ## Rebuild on changes
	deno run -A --watch main.ts &
	while true; do \
		make build-pages; \
		inotifywait -qre close_write typ; \
	done

start: ## Start the server
	deno run -A main.ts

fmt: ## Format the code
	deno fmt
