name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
           sudo npm i -g wasm-pack
           sudo apt install sassc
           ./build.sh

      - name: Deploy to `gh-pages`
        run: |
        git checkout gh-pages
        git add .
        git commit -am "auto deploy"
        git push origin gh-pages

      